In [ ]:
#MacroEdtech Online educational services


In [ ]:
# **********Linear Algebra in Python ***********#


**Linear Algebra is central and important in almost all areas
of mathematics**

• Linear Algebra is the “Mathematics of Data“

• Foundation: Vectors and Matrices

• Linear Equations

• Modern statistics and data analysis depends on Linear
Algebra

• Linear Algebra plays an important role in advanced
Control Engineering

• Linear Algebra plays an important role in Machine
Learning

In [ ]:
#Let's use the Array feature in the NumPy Library#

In [8]:
import numpy as np
a = np.array([[1],
[3],
[7],
[2]])
print("a =", a)
A = np.array([[1, 3, 7, 2],
[5, 8, -9, 0],
[6, -7, 11, 12]])
print("A =", A)

a = [[1]
 [3]
 [7]
 [2]]
A = [[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]


In [ ]:
#Matrix Addition, Subtraction, Multiplication#


In [6]:
import numpy as np
A = np.array([[0, 1],
[-2, -3]])
B = np.array([[1, 0],
[3, -2]])
C = A + B
print("A+B =", C)
C = A - B
print("A-B =", C)
C = A.dot(B)
print("A*B =", C)

A+B = [[ 1  1]
 [ 1 -5]]
A-B = [[-1  1]
 [-5 -1]]
A*B = [[  3  -2]
 [-11   6]]


In [ ]:
#Example number 3

In [7]:
import numpy as np
A = np.array([[1, 5, 3],
[4, 6, 6],
[3, 8, 9]])
B = np.array([[1, 5, 3, 4],
[4, 5, 7, 8],
[7, 8, 9, 3]])
C = np.array([[1],
[4],
[3]])
D = np.array([[1, 5, 3]])
M = np.matmul(A,B)
print("M=", M)
#M = np.matmul(B,A) # Not Working!
M = np.matmul(A,C)
print("M=", M)
#M = np.matmul(C,A) # Not Working!
M = np.matmul(C,D)
print("M=", M)
M = np.matmul(D,C)
print("M=", M)

M= [[ 42  54  65  53]
 [ 70  98 108  82]
 [ 98 127 146 103]]
M= [[30]
 [46]
 [62]]
M= [[ 1  5  3]
 [ 4 20 12]
 [ 3 15  9]]
M= [[30]]
